### ISSUE TITLE
The way we deliver changes

### ISSUE THREAD

**Issue by kermit10000000** [JaroslawWiosna/regionalizer#104]
#### Description

Since we seem to have problems with delivered code it might be the case that we do not check it enough and in the future with bigger structure we might make more and more bugs. So i have two questions that are also a proposal.
1. We could decide to make a rule about delivering new feature in code only with additional unit tests. In that way we will find and test in early stages the bugs that we know might happened or we think might happened. Also it will be additional info in the future if we get a problem that we do not test.
2. The way we handle bugs. I belive that in each case we find that bug requires fixes in the code we should after fixing it also add a unittest for this single case to make sure we won't have it in the future or that it did not happened in the same place(in case of similar bug). 

I ask for your opinion @JaroslawWiosna 
--- 

#### Release affected

Well maybe not this one(althought should be) but in case of an agreement it would be a requirement for all the next releases.

---

#### Priority

-

---

#### Is there possible contributor who could fix the issue

Well each contributor

---

**Comment by JaroslawWiosna** [comment]
@kermit10000000 Yes, you are right.
New changes should be integrated to `master` only when contributor delivers coresponding tests.

The reason we are not orthodox about this rule is because the whole project is `v0.x.x` version.
It is quite obvious that release `v1.0.0` is getting closer and closer, so it is important for us to follow this *unittested pull requests* rule.

I would be glad if you could start working on it by #96 in the first place.

**Comment by kermit10000000** [comment]
yeah ok  i will change the order i will be handling issues. Ok so if we have similar idea about this i also close this issue(if I am wrong please re-open it)
